#include <stdio.h>
#include "stack.h"
/* gcc with Stack.c */

/********************************************
*   *stack can't be generated by function   *
*********************************************/

void showdate(Item item) {
	printf("%d\t", item.date);
}

int main (void) {
	Item temp;	
	Stack Stack = NULL;
	InitializeStack(&Stack);
	puts("please enter num (q to quit)");
	while (scanf("%d", &temp.date)) {
		Push(&Stack, temp);	
	}	
	Traverse(&Stack, (*showdate));	
	Item itemOut = Pop(&Stack);	
	printf("after Pop\n");
	Traverse(&Stack, (*showdate));
	puts("show out");
	showdate(itemOut);
	pritnf("\n");
/*	int count = 0;
	Node *pnode = Stack;
	while (pnode != NULL) {
		count++;	
		pnode = pnode->next;
	}
	printf("count = %d\n", count);
*/
/*Node *t = *pStack;
	int cnt = 0;
	while (t->next != NULL)
	{
		cnt++;	
		t = t->next;
	}
	//Traverse(pStack, *(showdate));
	printf("%d\n", cnt);
*/
/*	if (isEmpty(pStack))
		printf("empty\n");
	else
		printf("not empty\n");
*/
/*	Item temp2;
	Push(pStack, temp);
	Push(pStack, temp2);
	Pop(pStack);
	isFull(pStack);	
*/
/*	while (scanf("%d", &temp.date)) {
		Push(pStack, temp);	
	}
*/
/*	if (isFull(pStack))
		printf("Full\n");
	else
		printf("Not Full\n");
*/

/*	if (isEmpty(pStack))
		printf("empty\n");
	else
		printf("not empty\n");
*/
	return 0;
}
